site_name: riadocs
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  logo: assets/icon_32x32.png
  favicon: assets/icon_32x32.png
  features:
    - navigation.instant
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg