site_name: riadocs
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  logo: assets/logo2.png
  favicon: assets/icon_32x32.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  consent:
    title: Cookie consent
    description: >- 


      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.com/invite/6PRt4Ph
      name: My Discord Server

    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/riasuh_
      name: My Twitter

    - icon: fontawesome/brands/github 
      link: https://github.com/riasuh
      name: My Github

    - icon: fontawesome/brands/youtube
      link: https://youtube.com/c/riasuh
      name: My Youtube

    - icon: fontawesome/brands/twitch 
      link: https://www.twitch.tv/riasuh
      name: My Twitch

copyright: Copyright &copy; 2022 riasuh
    